insta_proj/urls.py
# project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('user_profile.urls')),
    path('photos/', include('posts.urls')),
    path('interact/', include('interact.urls')),
    # Add more app-specific URLs as needed
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

posts/urls.py
# photos/urls.py
from django.urls import path
from .views import upload_photo
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('upload_photo/', upload_photo, name='upload_photo'),
    # Add more photo-related URLs as needed
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user_profile/urls.py
# users/urls.py
from django.urls import path
from.import views
from .views import edit_profile, view_profile, index, view_follow

app_name = "user_profile"

urlpatterns = [
    path("", index, name='index'),
    path ("UserProfile/", views.index_view, name=" UserProfile"),
    path('follow/<int:user_id>/', view_follow, name='toggle_follow'),
    path('edit/', edit_profile, name='edit_profile'),
    path('view/', view_profile, name='view_profile'),
    path("signup/", views.sign_up, name="sign_up"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    # Add more user-related URLs as needed
    
]

user_profile/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name="userProfile")
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)

class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
    followed_user = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE)

user_profile/forms.py
# forms.py
from django import forms
from .models import UserProfile, Follow

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio', 'profile_picture']

class FollowForm(forms.ModelForm):
    class Meta:
        model = Follow
        fields = ['followed_user']

user_profile/views.py
# views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import FollowForm, UserProfileForm
from .models import UserProfile, Follow

def index (request):
    return render(request, "user_profile/index.html")


def sign_up(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('user_profile:index')) 
        return render(request, "user_profile/instagram_signup.html")
    elif request.method == "POST":
        user = User.objects.create_user(
            username=request.POST.get('username'),
            email=request.POST.get('email'),
            password=request.POST.get('password'),
        )
        return HttpResponseRedirect(reverse('user_profile:login')) 

def login_view(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('user_profile:index')) 
        return render(request, "user_profile/instagram_login.html")
    elif request.method == "POST":
        username = request.POST.get('username') # POST["username"]
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('user_profile:index')) 
        else:
            return render(request, "user_profile/instagram_login.html", {"login_message": "Username/password is incorrect"})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_profile:login')) 


@login_required
def edit_profile(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        # Use the existing UserProfile instance or the newly created one
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('user_profile:view_profile')
    else:
        form = UserProfileForm(instance=user_profile)
    return render(request, 'user_profile/edit_profile.html', {'form': form})


@login_required
def view_profile(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)
    return render(request, 'user_profile/view_profile.html', {'user_profile': user_profile})



def index_view (request):
    UserProfile = UserProfileForm()
    return render(request, 'user_profile/index.html', { 'form': UserProfile })

@login_required
def form_submit(request):
    form = UserProfileForm(request.POST)
    if form.is_valid():
        form.save()
        return render(request, 'user_profile/view_profile.html', {})
    else:
        return render(request, 'user_profile/index.html', {'form': form})

@login_required
def view_follow(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        follow_form = FollowForm(request.POST)
        if follow_form.is_valid():
            user_to_follow_id = follow_form.cleaned_data['user_to_follow']
            user_to_follow = get_object_or_404(UserProfile, id=user_to_follow_id).user

            if user_to_follow != request.user:
                if user_to_follow in user_profile.followers.all():
                    user_profile.followers.remove(user_to_follow)
                else:
                    user_profile.followers.add(user_to_follow)

            return redirect('user_profile:view_profile')
    else:
        follow_form = FollowForm()

    return render(request, 'user_profile/view_profile.html', {'user_profile': user_profile, 'follow_form': follow_form})
    

user_profile/templates/user_profile/edit_profile.html
{% block content %}
  <h2>Edit Profile</h2>
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save Profile</button>
  </form>
{% endblock %}

user_profile/templates/user_profile/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Index </title>
</head>
<body>
    <h1> This is index page </h1>
    
    <p><a href="{% url "posts:upload_photo" %}">Upload Photo</a></p>
    <p> <a href="{% url "user_profile:view_profile" %}"> Profile </a> </p>  
    
</body>
</html>

user_profile/templates/user_profile/instagram_login.html
<h1> Login </h1>
<form action="{% url 'user_profile:login' %}" method="post">
    {% csrf_token %}
    {% if login_message %}<p style="color: red"><strong>{{ login_message }}</strong></p>{% endif %}
    <label for="username">Username: </label>
    <input type="text" value="" name="username"> <br/><br/>
    <label for="email">Password: </label>
    <input type="password" value="" name="password"> <br/><br/>
    <input type="submit" value="Login" id="login">
</form>

user_profile/templates/user_profile/instagram_signup.html
<h1> Register </h1>
<form action="{% url 'user_profile:sign_up' %}" method="post">
    {% csrf_token %}
    {% if register_message %}<p style="color: red"><strong>{{ register_message }}</strong></p>{% endif %}
    <label for="fname">First name: </label>
    <input type="text" value="" name="fname"> <br/><br/>
    <label for="lname">Last Name: </label>
    <input type="text" value="" name="lname"> <br/><br/>
    <label for="email">Email: </label>
    <input type="email" value="" name="email"> <br/><br/>
    <label for="username">Username: </label>
    <input type="text" value="" name="username"> <br/><br/>
    <label for="password">Password: </label>
    <input type="password" value="" name="password"> <br/><br/>
    <input type="submit" value="Register" id="register">
</form>

user_profile/templates/user_profile/view_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
</head>
<body>
    <!-- view_profile.html -->
    <h2>{{ user.username }}</h2>
    <p>{{ user_profile.bio }}</p>
    <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture">
    
    {% if user != user_profile.user %}
     <form method="post" action="{% url 'user_profile:view_profile' %}">
        {% csrf_token %}
        {{ follow_form.as_p }}
        <button type="submit">
            {% if user_profile.user in user.followers.all %}
                Unfollow
            {% else %}
                Follow
            {% endif %}
        </button>
     </form>
    {% endif %}


    <a href="{% url 'user_profile:edit_profile' %}"> Edit Profile </a>

</body>
</html>